service: exagonal-serverless-ts

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - ${self:custom.marcaTableArn}


plugins:
  - serverless-openapi-documentation
  - serverless-offline
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
  marcaTableArn: arn:aws:dynamodb:us-east-1:171267240569:table/MarcaTable
  documentation:
    version: 1.0.0
    title: Api-Serverless-NodeJs
    endpoints:
      - path: /api/marcas/{id}
        method: get
        functionName: serviceGetMarca
        description: Endpoint para obtener una marca por su ID


functions:
  servicePostCliente:
    handler: src/app/infrastructure/bootstrap/App.crearClienteHandler
    events:
      - httpApi:
          path: /api/marca
          method: post

  buscarCliente:
    handler: src/app/infrastructure/bootstrap/App.listarMarcasHandler
    events:
      - httpApi:
          path: /api/marca
          method: get
   


resources:
  Resources:
    usuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: MarcaTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH